name: Prettier

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    prettier:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Run prettier
              run: npm run CI_prettier

            - name: Run actual reformat if bad
              run: npm run CI_prettier -- -w
              if: ${{ failure() }}

            - name: Show diff
              run: git diff
              if: ${{ failure() }}
